apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: website-deployment