apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: website-deployment
  name: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: website-deployment
    spec:
      containers:
      - image: edwardallen/ecom-web@sha256:dc25db2cecf47348c09cf5413d94a5ccddb79cd5fafa5b8b2e57966af5443e88
        name: ecom-web
        ports:
        - containerPort: 80
        resources: {}
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: website-configmap
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: website-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: website-secret
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: website-configmap
              key: DB_NAME
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: feature-toggle-config
              key: FEATURE_DARK_MODE
        livenessProbe:
          httpGet:
            path: /healthcheck.php
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /db_healthcheck.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
status: {}
