apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: website-deployment
  name: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: website-deployment
    spec:
      containers:
      - image: edwardallen/ecom-web@sha256:54ca69e757c815f7575b7e7683677e8a8cd4b9f567e0bb4a21bba572644de664
        name: ecom-web
        ports:
        - containerPort: 80
        resources: {}
        env:
        - name: DB_HOST
          value: "mariadb-service"
        - name: DB_USER
          value: "ecomuser"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: website-secret
              key: password
        - name: DB_NAME
          value: "ecomdb"
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: feature-toggle-config
              key: FEATURE_DARK_MODE
status: {}
