{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
{{- if .Values.database.replicas }}
  replicas: {{ .Values.database.replicas | default 1 }}
{{- else }}
  replicas: {{ .Values.replicaCount | default 1 }}
{{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.database.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.database.labels | nindent 8 }}
    spec:
      containers:
        - name: ecom-db
          image: {{ .Values.database.image | default "mariadb" | quote }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.database.port | default 3306 }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.secret.fullname | quote }}
                key: password
          resources: {}
          volumeMounts:
            - name: mariadb-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-initdb
          configMap:
            name: {{ .Values.database.configmap.initsql.fullname | quote }}
{{- end }}
