{{- if .Values.database.enabled }}
apiVersion: v1
data:
  password: YWRtaW4xMjM0NSE=
  username: cm9vdA==
kind: Secret
metadata:
  name: {{ .Values.database.secret.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
{{- end }}
