{{- if .Values.website.enabled }}
apiVersion: v1
data:
  password: RiFoRzE3Y1k3ZXczRSpSWQ==
kind: Secret
metadata:
  name: {{ .Values.website.secret.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
{{- end }}
