apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: website-deployment
  name: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: website-deployment
    spec:
      containers:
      - image: docker.io/edwardallen/ecom-web:v1
        name: ecom-web
        ports:
        - containerPort: 80
        resources: {}
status: {}
