name: Deploy Docker Image and Deploy to EKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
        docker build -t "edwardallen/ecom-web:v1" .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Registry
      run: |
        docker push "edwardallen/ecom-web:v1"

  package_and_deploy_helm_chart:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Package Helm Chart
      run: |
        cd kubernetes/
        helm package ecommerce-website
        cd ecommerce-website/ 
        helm lint

    - name: Deploy Helm Chart
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.9
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        cluster-name: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
        chart-path: kubernetes/
        name: ecommerce-website
  
    
