# Default values for ecommerce-website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: ecommerce

database: 
  enabled: true
  fullname: ecom-db
  replicas: 1
  image: mariadb
  labels:
    app: ecom-db

  service:
    fullname: ecom-db-service
    type: ClusterIP
    port: 3306
  
  secret:
    fullname: ecom-db-secret
  
  configmap:
    initsql:
      fullname: ecom-db-initdb-config
  
  storage:
    persistentVolumeName: ecom-db-pv
    persistentVolumeClaimName: ecom-db-pvc
  
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 300Mi


website:
  enabled: true
  fullname: ecom-web
  replicas: 1
  image: edwardallen/ecom-web@sha256:dc25db2cecf47348c09cf5413d94a5ccddb79cd5fafa5b8b2e57966af5443e88
  port: 80
  labels:
    app: ecom-web
  
  service:
    fullname: ecom-web-service
    type: LoadBalancer
    port: 80
  
  secret:
    fullname: ecom-web-secret
  
  configmap:
    env:
      fullname: ecom-web-configmap
    featureToggle:
      fullname: feature-toggle-config

  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 300Mi

autoscaling:
  enabled: true
  hpa:
    fullname: ecom-app-hpa
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 95
    targetMemoryUtilizationPercentage: 95

test:
  enabled: false

  # image: 
  #   repository: ""
  #   pullPolicy: IfNotPresent
  #   # Overrides the image tag whose default is the chart appVersion.
  #   tag: ""

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

# serviceAccount:
#   # Specifies whether a service account should be created
#   create: false
#   # Annotations to add to the service account
#   annotations: {}
#   # The name of the service account to use.
#   # If not set and create is true, a name is generated using the fullname template
#   name: ""

# podAnnotations: {}

# podSecurityContext: {}
#   # fsGroup: 2000

# securityContext: {}
#   # capabilities:
#   #   drop:
#   #   - ALL
#   # readOnlyRootFilesystem: true
#   # runAsNonRoot: true
#   # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

# # ingress:
# #   enabled: false
# #   className: ""
# #   annotations: {}
# #     # kubernetes.io/ingress.class: nginx
# #     # kubernetes.io/tls-acme: "true"
# #   hosts:
# #     - host: chart-example.local
# #       paths:
# #         - path: /
# #           pathType: ImplementationSpecific
# #   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

# resources: {}
#   # We usually recommend not to specify default resources and to leave this as a conscious
#   # choice for the user. This also increases chances charts run on environments with little
#   # resources, such as Minikube. If you do want to specify resources, uncomment the following
#   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   # limits:
#   #   cpu: 100m
#   #   memory: 128Mi
#   # requests:
#   #   cpu: 100m
#   #   memory: 128Mi



# nodeSelector: {}

# tolerations: []

# affinity: {}
